export const PROCESS_CODES = {
  APPROVED_DIGITAL: 'APPROVED_DIGITAL',
  APPROVED_BRANCH_CALL: 'APPROVED_BRANCH_CALL',
  REJECTED_NO_CONSENT: 'REJECTED_NO_CONSENT',
  RESTRICTED_STAFF: 'RESTRICTED_STAFF',
  ERR_VALIDATION_FAILED: 'ERR_VALIDATION_FAILED',
  ERR_SYSTEM_INTERNAL: 'ERR_SYSTEM_INTERNAL',
} as const;

export type ProcessCodeType = typeof PROCESS_CODES[keyof typeof PROCESS_CODES];
